title: "AI for Dev"
description: "A guide on how to run Large Language Models (LLMs) locally for coding assistance."
remote_theme: just-the-docs/just-the-docs
search_enabled: true

# Base URL and Repository Settings
baseurl: "/ai-for-dev"  # or set to "" if in the root directory
url: "https://jessefreeman.github.io"

# Sidebar Navigation
just_the_docs:
  aux_links:
    "GitHub Repository": "https://github.com/jessefreeman/ai-for-dev"
  show_toc: true
  toc_levels: "1,2,3"
  repository_url: "https://github.com/jessefreeman/ai-for-dev"
  edit:
    enabled: true  # Enable the Edit on GitHub link
    base_url: "https://github.com/jessefreeman/ai-for-dev/edit/main/"  # URL for editing the file

# Enable plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Footer settings
footer_content: |
  <p><strong>AI for Dev</strong> - A guide to running LLMs for coding assistance locally.</p>
  <p>Find more resources on <a href="https://github.com/jessefreeman/ai-for-dev">GitHub</a>.</p>

# Edit timestamp and link
last_edit_timestamp: true  # Show last edit timestamp on pages
last_edit_time_format: "%b %e %Y at %I:%M %p"  # Format for last edit timestamp
back_to_top: true  # Show "Back to top" link at the bottom of every page

# Heading anchors (links next to headings)
heading_anchors: true

# Copy button for code snippets
enable_copy_code_button: true
