title: "AI for Dev"
description: "A guide on how to run Large Language Models (LLMs) locally for coding assistance."
theme: jekyll-theme-architect

# Link to your custom CSS
includes:
  - /styles/custom.css